### ISSUE TITLE
Feature request - long read assembly graphs

### ISSUE THREAD

**Issue by susheelbhanu** [Vini2/GraphBin#2]
Hey all, 

Thanks a for a great tool. I was wondering if you have any plans or works in the pipeline to be able to use this for long-read assemblies. 

Thanks again!

**Comment by anuradhawick** [comment]
Hi @susheelbhanu 

Assemblers have different formats for the graph. Could you be specific with the type of assembler(s) that you plan to use with GraphBin?

Kindly note that we have developed the tool for Illumina short reads and the long reads assemblies might have sparsely connected graphs. This can make the label propagation less effective. Let us know the assembler then we are happy to help how to proceed. 

Thanks

**Comment by susheelbhanu** [comment]
@anuradhawick: I was thinking of flye and canu. Thank you for helping with this!

**Comment by Niicii** [comment]
+1 for Flye and maybe Miniasm as well

**Comment by Vini2** [comment]
Hi @susheelbhanu and @Niicii,

We have updated the GraphBin functionality so that GraphBin can work with Flye and Canu assemblies. Kindly note that since the assembly graph of Flye consists of edges (not the final contigs) we have used the assembly graph with edges and the corresponding edge sequences. We have also added a support script [flye_gfa2fasta.py](https://github.com/Vini2/GraphBin/blob/master/support/flye_gfa2fasta.py) to extract the edge sequences from the assembly graph file. Moreover, we are working on Miniasm functionality as well.

As @anuradhawick has mentioned, kindly note that we have developed GraphBin for Illumina short reads and the long-read assemblies might have sparsely connected graphs. This can make the label propagation less effective and may not result in improvements.

Thank you for your interest in our tool!

**Comment by susheelbhanu** [comment]
Thanks a lot @Vini2. I'll give this a try and let you know if I run into any issues.

Best regards!!

**Comment by Vini2** [comment]
Hi @Niicii,

We have updated the GraphBin functionality so that GraphBin can work with Miniasm assemblies. Kindly note that since the assembly graph of Miniasm consists of unitig sequences we have used the assembly graph with unitig sequences. We have also added a support script [flye_miniasm_gfa2fasta.py](https://github.com/Vini2/GraphBin/blob/master/support/flye_miniasm_gfa2fasta.py) to extract the unitig sequences from the Miniasm assembly graph file.

Thank you for your interest in our tool!
