### ISSUE TITLE
graphbin_SPAdes.py path and ModuleNotFoundError: No module named 'igraph'

### ISSUE THREAD

**Issue by michaelwoodworth** [Vini2/GraphBin#7]
Hi, I recently heard about your tool and am hoping it can improve some of my binning results.

I cloned the version on github today (July 17 2020) and installed following the recommendations on the wiki.  I have encountered a couple of errors that may be easy to resolve but wanted to share.

1 - I think the path to the assembler-specific scripts may be missing a forward slash. i got the following Errno 2:

python ${path}/apps/GraphBin/graphbin.py --assembler spades --graph assembly_graph_with_scaffolds.gfa --paths contigs.paths --binned ../initial_contig_bins.csv --output ../../gb_bins/
python: can't open file '${path}/apps/GraphBinsrc/graphbin_SPAdes.py': [Errno 2] No such file or directory

Looking in the graphbin.py script, I added a forward slash in the SPAdes section so it points to: ${path}/apps/GraphBin/src/graphbin_SPAdes.py

which worked.

2 - then I got a missing module error:

 python ${path}//apps/GraphBin/graphbin.py --assembler spades --graph assembly_graph_with_scaffolds.gfa --paths contigs.paths --binned ../initial_contig_bins.csv --output ../../gb_bins/
Traceback (most recent call last):
  File "${path}//apps/GraphBin/src/graphbin_SPAdes.py", line 24, in <module>
    from igraph import *
ModuleNotFoundError: No module named 'igraph'

I'm working on a cluster and was able to install igraph locally and get GraphBin to run but wanted to share this in case others have these issues.

**Comment by alienzj** [comment]
`conda install python-igraph`

**Comment by anuradhawick** [comment]
@michaelwoodworth Thanks for your query. We have updated the code with the help of @alienzj that makes installation much easier for everybody including non-computer scientists.

With referencing to your cluster environment, one solution would be to install graphbin as user with `pip3 install . --user`. This is possible with our new release. However, if you still cannot install I have 2 workarounds that we use in our cluster NCI Australia.

1. Using conda environments.

This way you can install conda to a location on the cluster that you have permission and initialize in bash_rc. Go to [Anaconda Website](https://www.anaconda.com/products/individual) and download the installer. Then run `sh ANACONDA_INSTALLER.sh`. Afterwards, you can use conda command from your login node and install dependencies and run GraphBin code without having to run pip install. Make sure you install all dependencies to your conda environment before you run graphbin.

2. Using Linux modules and a python path in your project space in the cluster.

However, using conda might not help you in a cluster due to inode limitations. So you can follow the following steps. Assuming you have Linux modules in your cluster.
```
module load python/3.7
pip install -v --no-binary :all: --prefix=/short/your/directory/name .
```

Most likely when you import the python module pip3 will be aliased to pip in the cluster. This command will install graphbin in path `/short/your/directory/name`. Then in your job script please add the following.

Please run `module avail python` to ensure you have a python 3+ version in the cluster to load.

Please let us know if there are more issues popping. We are happy to help always.

```
module load python/3.7
export PYTHONPATH=$PYTHONPATH:/short/your/directory/name/lib/python3.7/site-packages
export PATH=$PATH:/short/your/directory/name/bin
```

Then you'll have access to graphbin program. This could be the most desired option considering the nature of file systems in clusters and inode limitation. I hope this helps you with your research work! Cheers. 👍

**Comment by Vini2** [comment]
Closing this issue after improving the code.
